-- 能量工作室：優惠碼系統
-- 請在 Supabase SQL Editor 執行一次。

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null check (type in ('percent','fixed')),
  value numeric(10,2) not null check (value > 0),
  active boolean not null default true,
  expires_at timestamptz,
  max_uses integer not null default 0 check (max_uses >= 0),
  one_per_user boolean not null default false,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.coupon_redemptions (
  id bigint generated by default as identity primary key,
  coupon_id bigint not null references public.coupons(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  discount_amount numeric(10,2) not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists coupon_redemptions_one_user_idx
on public.coupon_redemptions(coupon_id, user_id)
where user_id is not null;

create index if not exists coupons_code_idx on public.coupons(lower(code));
create index if not exists coupon_redemptions_coupon_idx on public.coupon_redemptions(coupon_id);

alter table public.coupons enable row level security;
alter table public.coupon_redemptions enable row level security;

revoke all on table public.coupons from anon, authenticated;
revoke all on table public.coupon_redemptions from anon, authenticated;

drop policy if exists "admins can manage coupons" on public.coupons;
create policy "admins can manage coupons"
on public.coupons for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins can read coupon redemptions" on public.coupon_redemptions;
create policy "admins can read coupon redemptions"
on public.coupon_redemptions for select
to authenticated
using (public.is_admin());

grant select, insert, update, delete on public.coupons to authenticated;
grant select on public.coupon_redemptions to authenticated;
