-- 能量工作室：客戶帳號 + 個人優惠
-- 請在 Supabase SQL Editor 執行一次。

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.discounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('percent','fixed')),
  value numeric(10,2) not null check (value >= 0),
  active boolean not null default true,
  expires_at timestamptz,
  note text,
  created_at timestamptz not null default now()
);

alter table public.orders add column if not exists user_id uuid references auth.users(id);
alter table public.orders add column if not exists original_price numeric(10,2);
alter table public.orders add column if not exists discount_amount numeric(10,2) not null default 0;

create index if not exists profiles_email_idx on public.profiles(lower(email));
create index if not exists profiles_display_name_idx on public.profiles(lower(display_name));

alter table public.profiles enable row level security;
alter table public.discounts enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, nullif(new.raw_user_meta_data->>'display_name', ''))
  on conflict (id) do update
    set email = excluded.email,
        display_name = coalesce(public.profiles.display_name, excluded.display_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "admins can read all profiles" on public.profiles;
create policy "admins can read all profiles"
on public.profiles for select
to authenticated
using (public.is_admin() or auth.uid() = id);

drop policy if exists "users can read own discounts" on public.discounts;
create policy "users can read own discounts"
on public.discounts for select
to authenticated
using (auth.uid() = user_id);

-- 客戶可以建立自己的訂單；原有匿名查詢/下單流程如需保留，可按現有 policies 調整。
-- 優惠的真正價格計算會在 Vercel API + service role 端完成，前端不能自行改價。


drop policy if exists "admins can manage discounts" on public.discounts;
create policy "admins can manage discounts"
on public.discounts for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- 執行完成後，把你自己的管理員帳號升級（把 Email 換成你的 Admin Email）：
-- update public.profiles set role = 'admin' where email = 'YOUR_ADMIN_EMAIL';
